/* ===========================================================================
 * bitwise_tricks.c
 *
 * Code generated by AI
 *
 * A tour of "party tricks" and everyday idioms built from C's bitwise
 * operators:  &  |  ^  ~  <<  >>
 *
 * This is written as a companion to K&R "The C Programming Language",
 * Chapter 2 (Bitwise Operators section, 2.9). Every trick below is
 * explained step-by-step in comments so you don't have to squint at
 * cryptic one-liners to understand *why* they work.
 *
 * Quick refresher on the operators (all work on the bit pattern of ints):
 *   &   AND   -> bit is 1 only if BOTH bits are 1   (used to CLEAR/TEST bits)
 *   |   OR    -> bit is 1 if EITHER bit is 1        (used to SET bits)
 *   ^   XOR   -> bit is 1 if bits DIFFER             (used to TOGGLE bits)
 *   ~   NOT   -> flips every bit                     (used to build masks)
 *   <<  shift left  -> multiply by 2 per shift, fills with 0 on the right
 *   >>  shift right -> divide by 2 per shift (careful with signed ints!)
 *
 * Compile:  cc -Wall -o bitwise_tricks bitwise_tricks.c
 * Run:      ./bitwise_tricks
 * ===========================================================================
 */

#include <stdio.h>

/* --------------------------------------------------------------------------
 * Small helper: prints an unsigned int as a fixed-width binary string.
 * Not a "trick" itself, just here so every demo below can *show* the bits
 * instead of only the decimal value -- seeing the bits is the whole point.
 * ------------------------------------------------------------------------ */
void print_bits(unsigned int x, int width)
{
    int i;
    /* Walk from the most significant bit (width-1) down to bit 0.
     * For each position, shift x right so that bit lands in position 0,
     * then mask with & 1 to read just that single bit. */
    for (i = width - 1; i >= 0; i--) {
        putchar((x >> i) & 1 ? '1' : '0');
        if (i % 4 == 0 && i != 0) putchar(' '); /* group in nibbles, cosmetic */
    }
}

void show(const char *label, unsigned int x)
{
    printf("%-28s = %5u   (binary: ", label, x);
    print_bits(x, 16); /* 16 bits is plenty to visualize for these demos */
    printf(")\n");
}

/* ===========================================================================
 * TRICK 1: Even or odd, without using % (modulo)
 *
 * In binary, the LAST bit (bit 0) of any integer tells you whether it's
 * even or odd -- exactly like the last digit of a decimal number tells you
 * the same thing in base 10 (0,2,4,6,8 = even).
 *
 * x & 1 isolates that last bit:
 *   ...0110  &  ...0001  =  0   -> even
 *   ...0111  &  ...0001  =  1   -> odd
 * ===========================================================================
 */
void demo_even_odd(int n)
{
    printf("%d is %s (n & 1 = %d)\n", n, (n & 1) ? "ODD" : "EVEN", n & 1);
}

/* ===========================================================================
 * TRICK 2: Swap two variables without a temporary, using XOR
 *
 * XOR has a beautiful property: it's its own inverse.
 *   a ^ b ^ b == a
 *   a ^ b ^ a == b
 *
 * So if we do:
 *   a = a ^ b;   // a now holds "the difference" between original a and b
 *   b = a ^ b;   // b becomes (orig_a ^ orig_b) ^ orig_b = orig_a
 *   a = a ^ b;   // a becomes (orig_a ^ orig_b) ^ orig_a = orig_b
 * we swap them with zero extra memory.
 *
 * NOTE: this is a fun party trick, but in real code just use a temp
 * variable -- it's clearer, and this XOR trick FAILS if a and b are the
 * same memory location (you'd XOR it to zero and lose the value).
 * ===========================================================================
 */
void demo_xor_swap(void)
{
    int a = 7, b = 42;
    printf("Before swap: a = %d, b = %d\n", a, b);

    a = a ^ b;
    b = a ^ b;
    a = a ^ b;

    printf("After  swap: a = %d, b = %d\n", a, b);
}

/* ===========================================================================
 * TRICK 3: Check if a number is a power of two
 *
 * A power of two (1, 2, 4, 8, 16, 32...) has EXACTLY one bit set:
 *      8 = 0000 1000
 * Subtracting 1 flips that single set bit to 0 and turns every bit BELOW
 * it into 1:
 *  8-1 = 7 = 0000 0111
 * ANDing the two together always gives 0 for a true power of two, because
 * there's no overlap between "one bit set" and "everything below it set".
 *
 *      1000
 *    & 0111
 *    ------
 *      0000   -> zero means "yes, power of two"
 *
 * For a non-power-of-two like 6 (0110):
 *  6-1 = 5 = 0101
 *      0110
 *    & 0101
 *    ------
 *      0100   -> non-zero means "no"
 *
 * Special case: n must be > 0, since 0 - 1 underflows.
 * ===========================================================================
 */
void demo_power_of_two(unsigned int n)
{
    int is_pow2 = (n > 0) && ((n & (n - 1)) == 0);
    printf("%u is %sa power of two\n", n, is_pow2 ? "" : "NOT ");
}

/* ===========================================================================
 * TRICK 4: Count the number of 1-bits (population count) -- Kernighan's trick
 *
 * This is literally attributed to Brian Kernighan (yes, the K in K&R!).
 * The key identity: x & (x - 1) clears the LOWEST set bit of x.
 *
 * Why? Subtracting 1 turns the lowest set bit into 0 and every bit below
 * it into 1 (same idea as Trick 3). ANDing with the original x keeps all
 * the untouched higher bits, but the lowest set bit disappears because
 * original had 1 there and (x-1) has 0 there.
 *
 * Example, x = 12 = 1100:
 *   x       = 1100
 *   x-1     = 1011
 *   x&(x-1) = 1000   <- lowest set bit (the 4's place) is gone
 *
 * Loop that off repeatedly and count how many times you could do it --
 * that count is the number of 1-bits. This runs in O(number_of_set_bits),
 * which is much faster than checking all 32 bits one by one when the
 * number is sparse (few bits set).
 * ===========================================================================
 */
int count_set_bits(unsigned int x)
{
    int count = 0;
    while (x != 0) {
        x = x & (x - 1); /* zap the lowest set bit */
        count++;
    }
    return count;
}

void demo_count_bits(unsigned int n)
{
    printf("%u has %d bit(s) set to 1\n", n, count_set_bits(n));
}

/* ===========================================================================
 * TRICK 5: Isolate the lowest set bit
 *
 * x & (-x) extracts ONLY the lowest 1-bit and zeroes everything else.
 *
 * Why does this work? In two's complement, -x is (~x + 1). Flipping all
 * bits of x and adding 1 has the effect of leaving all the trailing zero
 * bits of x untouched but flipping the lowest set bit and everything
 * above it. When you AND that against the original x, only the lowest
 * set bit survives because it's the only position where both x and -x
 * still have a 1.
 *
 * Example, x = 12 = 0000 1100
 *          -x     = 1111 0100  (two's complement)
 *   x & -x = 0000 0100 = 4     <- exactly the lowest set bit
 *
 * This trick is the heart of data structures like Fenwick trees (Binary
 * Indexed Trees), used to jump between "responsible ranges" quickly.
 * ===========================================================================
 */
void demo_isolate_lowest_bit(unsigned int n)
{
    unsigned int lowest = n & (-(int)n);
    printf("Lowest set bit of %u is %u\n", n, lowest);
}

/* ===========================================================================
 * TRICK 6: Turn ON / OFF / TOGGLE / TEST a single bit at position p
 *
 * These four operations are the absolute bread-and-butter of bit
 * manipulation -- flags, permission bits, hardware registers, etc.
 *
 *   Build a mask with a single 1 at position p:      mask = 1 << p
 *   SET bit p (force to 1):    x = x | mask
 *   CLEAR bit p (force to 0):  x = x & ~mask
 *   TOGGLE bit p (flip it):    x = x ^ mask
 *   TEST bit p (read it):      (x >> p) & 1
 * ===========================================================================
 */
void demo_bit_flags(void)
{
    unsigned int flags = 0; /* start with everything off: 0000 0000 */
    int p;

    show("start", flags);

    p = 3;
    flags = flags | (1u << p);  /* SET bit 3 */
    printf("Set bit %d ->\n", p);
    show("flags", flags);

    p = 6;
    flags = flags | (1u << p);  /* SET bit 6 too */
    printf("Set bit %d ->\n", p);
    show("flags", flags);

    p = 3;
    flags = flags & ~(1u << p); /* CLEAR bit 3 */
    printf("Clear bit %d ->\n", p);
    show("flags", flags);

    p = 6;
    flags = flags ^ (1u << p);  /* TOGGLE bit 6 (was 1, becomes 0) */
    printf("Toggle bit %d ->\n", p);
    show("flags", flags);

    p = 6;
    printf("Test bit %d -> %u\n", p, (flags >> p) & 1u);
}

/* ===========================================================================
 * TRICK 7: getbits -- extract n bits from position p (K&R exercise 2-6 idea)
 *
 * This is straight out of the K&R exercises. It returns the n bits that
 * are RIGHT-ADJUSTED starting at bit position p (counting bit 0 as the
 * rightmost bit).
 *
 * Steps:
 *   1. x >> (p + 1 - n)   -- shift the field of interest down so its
 *                            lowest bit lands at bit 0.
 *   2. ~(~0 << n)         -- build a mask of n ones. Start from all-ones
 *                            (~0), shift left by n (pushes n zero bits in
 *                            from the right), then flip everything: the
 *                            result is n ones followed by zeros... wait,
 *                            we then AND with the shifted value, so only
 *                            the low n bits of the shifted value remain.
 *   3. AND the two together to keep only those n bits.
 *
 * Example: getbits(0xF0, 7, 4) should pull out the nibble "1111"
 *          0xF0 = 1111 0000, bits 7..4 are the top nibble = 1111 = 0xF
 * ===========================================================================
 */
unsigned int getbits(unsigned int x, int p, int n)
{
    return (x >> (p + 1 - n)) & ~(~0u << n);
}

void demo_getbits(void)
{
    unsigned int x = 0xF0; /* 1111 0000 */
    unsigned int result = getbits(x, 7, 4); /* grab top nibble (bits 7-4) */
    show("x", x);
    printf("getbits(x, p=7, n=4) = %u (0x%X) -> top nibble extracted\n\n",
           result, result);
}

/* ===========================================================================
 * TRICK 8: setbits -- set n bits of x at position p to the low n bits of y
 * (companion to getbits, also inspired by the K&R exercises)
 *
 * Steps:
 *   1. Build a mask of n ones: ~(~0 << n)
 *   2. Shift that mask so the ones line up at position p: mask << (p+1-n)
 *   3. Clear those bits in x with x & ~mask_shifted
 *   4. Take the low n bits of y, shift them into position, OR them in.
 * ===========================================================================
 */
unsigned int setbits(unsigned int x, int p, int n, unsigned int y)
{
    unsigned int mask = ~(~0u << n);            /* n ones, e.g. n=4 -> 0000 1111 */
    unsigned int shifted_mask = mask << (p + 1 - n);
    unsigned int cleared = x & ~shifted_mask;    /* punch a hole of n zeros in x  */
    unsigned int field   = (y & mask) << (p + 1 - n); /* prep replacement bits    */
    return cleared | field;
}

void demo_setbits(void)
{
    unsigned int x = 0x00; /* 0000 0000 */
    unsigned int y = 0x0A; /* ...1010, we only care about its low 4 bits */
    unsigned int result = setbits(x, 7, 4, y); /* write y's low nibble into x's top nibble */
    show("x (before)", x);
    printf("setbits(x, p=7, n=4, y=0x%X) = %u (0x%X)\n\n", y, result, result);
}

/* ===========================================================================
 * TRICK 9: ASCII case toggle using a single bit
 *
 * This one is a genuine "party trick" from how ASCII was designed.
 * Uppercase and lowercase letters differ by EXACTLY one bit:
 *
 *   'A' = 0100 0001 (0x41)
 *   'a' = 0110 0001 (0x61)
 *                ^--- only bit 5 (value 0x20) differs
 *
 * So:
 *   XOR with 0x20  -> toggles case (A<->a, B<->b, ...)
 *   OR  with 0x20  -> forces lowercase (sets bit 5 to 1)
 *   AND with ~0x20 -> forces uppercase (clears bit 5 to 0)
 *
 * This only works for letters, not digits/punctuation, so real code
 * should still use toupper()/tolower() from <ctype.h> -- but it's a
 * great illustration of why bitwise tricks exist: the data format
 * itself was designed with bit patterns in mind.
 * ===========================================================================
 */
void demo_ascii_case_toggle(void)
{
    char c = 'k';
    printf("'%c' XOR 0x20 -> '%c'  (case toggled)\n", c, c ^ 0x20);
    printf("'%c' OR  0x20 -> '%c'  (forced lowercase)\n", 'K', 'K' | 0x20);
    printf("'%c' AND ~0x20 -> '%c' (forced uppercase)\n", 'k', 'k' & ~0x20);
}

/* ===========================================================================
 * TRICK 10: Multiply / divide by powers of two with shifts
 *
 * Shifting left by k is the same as multiplying by 2^k.
 * Shifting right by k is the same as dividing by 2^k (integer division,
 * and only safe/well-defined for non-negative numbers or when using
 * unsigned types -- right-shifting a NEGATIVE signed int is
 * implementation-defined behavior in C, so be careful).
 *
 * Compilers already do this optimization automatically for you when you
 * write "x * 4" -- so this trick is more about understanding what's
 * happening under the hood than something you should hand-write today.
 * ===========================================================================
 */
void demo_shift_multiply_divide(void)
{
    unsigned int x = 5;
    printf("%u << 1 = %u   (x * 2)\n", x, x << 1);
    printf("%u << 3 = %u   (x * 8)\n", x, x << 3);

    unsigned int y = 40;
    printf("%u >> 1 = %u   (y / 2)\n", y, y >> 1);
    printf("%u >> 3 = %u   (y / 8)\n", y, y >> 3);
}

/* ===========================================================================
 * TRICK 11: Detect if two integers have opposite signs, without an if
 *
 * XOR-ing two signed integers together: the SIGN BIT (the highest bit)
 * of the result is 1 exactly when the two original sign bits differed --
 * i.e. exactly when one number was negative and the other positive.
 *
 * We then just look at that sign bit. In a plain "int", checking
 * (a ^ b) < 0 is a fast, branch-light way to ask "do these differ in sign?"
 * ===========================================================================
 */
void demo_opposite_signs(int a, int b)
{
    int opposite = (a ^ b) < 0;
    printf("%d and %d have %s signs\n", a, b,
           opposite ? "OPPOSITE" : "the SAME");
}

/* ===========================================================================
 * TRICK 12: Find the one number that appears once in an array where every
 * other number appears exactly twice -- using only XOR
 *
 * Recall: x ^ x = 0, and x ^ 0 = x, and XOR is commutative/associative.
 * So if you XOR every element of the array together, every PAIR of
 * duplicates cancels itself out to 0, and whatever is left over is the
 * lone, unpaired number. No extra memory, one single pass, O(n) time.
 * ===========================================================================
 */
void demo_find_unique(void)
{
    int arr[] = {4, 1, 2, 1, 2}; /* 4 is the only one without a pair */
    int n = sizeof(arr) / sizeof(arr[0]);
    int i, result = 0;

    for (i = 0; i < n; i++) {
        result ^= arr[i]; /* duplicates cancel out as we go */
    }

    printf("Array: {4, 1, 2, 1, 2} -> unique element = %d\n", result);
}

/* ===========================================================================
 * TRICK 13: Absolute value without branching, using shift + XOR (two's
 * complement trick)
 *
 * Assumes a 32-bit int and two's complement representation (standard on
 * essentially every modern machine).
 *
 *   mask = x >> 31
 *     If x is negative, arithmetic right-shift by 31 fills with the sign
 *     bit, producing all 1s (i.e. mask = -1 = 0xFFFFFFFF).
 *     If x is non-negative, mask becomes all 0s (mask = 0).
 *
 *   (x + mask) ^ mask
 *     If mask is 0:        (x + 0) ^ 0  = x                (unchanged)
 *     If mask is all 1s:   (x + (-1)) ^ (-1) = -(x)          (negated)
 *       This is exactly the two's-complement recipe for negation:
 *       "subtract 1, then flip all bits" is the same as "flip all bits,
 *       then add 1" thanks to how carries interact with XOR -- both give
 *       you -x.
 *
 * NOTE: right-shifting a negative signed int is technically
 * implementation-defined in strict ISO C, though every mainstream
 * compiler (gcc, clang, msvc) implements it as arithmetic shift. This is
 * shown here as a classic trick, not a recommendation over abs()/labs().
 * ===========================================================================
 */
int fast_abs(int x)
{
    int mask = x >> 31;         /* all 1s if negative, all 0s if not */
    return (x + mask) ^ mask;
}

void demo_fast_abs(void)
{
    printf("fast_abs(-17) = %d\n", fast_abs(-17));
    printf("fast_abs( 17) = %d\n", fast_abs(17));
}

/* ===========================================================================
 * TRICK 14: Reverse the bits of a byte
 *
 * Classic "look-busy-at-a-party" trick. We build the result bit-by-bit:
 * take the lowest bit of x, drop it into the highest available slot of
 * the result, then shift both x right and result left, repeating 8 times
 * for a byte.
 *
 * Example idea (not full trace): 1011 0000 reversed becomes 0000 1101
 * ===========================================================================
 */
unsigned char reverse_byte(unsigned char x)
{
    unsigned char result = 0;
    int i;
    for (i = 0; i < 8; i++) {
        result = (result << 1) | (x & 1); /* push in x's current lowest bit */
        x >>= 1;                          /* move on to the next bit of x   */
    }
    return result;
}

void demo_reverse_bits(void)
{
    unsigned char x = 0xB0; /* 1011 0000 */
    unsigned char r = reverse_byte(x);
    printf("reverse_byte(0x%02X) = 0x%02X  ", x, r);
    printf("(");
    print_bits(x, 8);
    printf("  ->  ");
    print_bits(r, 8);
    printf(")\n");
}

/* ===========================================================================
 * TRICK 15: Rotate bits left (circular shift) within a byte
 *
 * A plain "<<" shift LOSES the bits that fall off the left edge. A
 * ROTATION instead wraps them back around to the right edge, so no
 * information is lost -- useful in hashing and simple cryptography.
 *
 * To rotate an 8-bit value left by k:
 *   - shift left by k normally (top k bits fall off the 8-bit window)
 *   - separately shift right by (8-k) to bring exactly those "fallen off"
 *     bits back around to the bottom
 *   - OR the two pieces together
 *   - mask with 0xFF to stay within one byte
 * ===========================================================================
 */
unsigned char rotate_left_byte(unsigned char x, int k)
{
    return (unsigned char)(((x << k) | (x >> (8 - k))) & 0xFF);
}

void demo_rotate(void)
{
    unsigned char x = 0x85; /* 1000 0101 */
    unsigned char r = rotate_left_byte(x, 3);
    printf("rotate_left_byte(0x%02X, 3) = 0x%02X  ", x, r);
    printf("(");
    print_bits(x, 8);
    printf("  ->  ");
    print_bits(r, 8);
    printf(")\n");
}

/* ===========================================================================
 * main -- runs every demo in order, with headers so the output reads like
 * a guided tour rather than a wall of text.
 * ===========================================================================
 */
int main(void)
{
    printf("=== 1. Even/Odd check (n & 1) ===\n");
    demo_even_odd(17);
    demo_even_odd(42);
    printf("\n");

    printf("=== 2. XOR swap (no temp variable) ===\n");
    demo_xor_swap();
    printf("\n");

    printf("=== 3. Power-of-two check (n & (n-1)) ===\n");
    demo_power_of_two(64);
    demo_power_of_two(50);
    printf("\n");

    printf("=== 4. Count set bits (Kernighan's trick) ===\n");
    demo_count_bits(29); /* 29 = 0001 1101 -> four 1-bits */
    printf("\n");

    printf("=== 5. Isolate the lowest set bit (x & -x) ===\n");
    demo_isolate_lowest_bit(44); /* 44 = 0010 1100 */
    printf("\n");

    printf("=== 6. Set/Clear/Toggle/Test a single bit ===\n");
    demo_bit_flags();
    printf("\n");

    printf("=== 7. getbits: extract a bit field (K&R style) ===\n");
    demo_getbits();

    printf("=== 8. setbits: write into a bit field (K&R style) ===\n");
    demo_setbits();

    printf("=== 9. ASCII case toggle via bit 0x20 ===\n");
    demo_ascii_case_toggle();
    printf("\n");

    printf("=== 10. Multiply/divide by powers of two via shifts ===\n");
    demo_shift_multiply_divide();
    printf("\n");

    printf("=== 11. Opposite-sign check via XOR ===\n");
    demo_opposite_signs(-5, 10);
    demo_opposite_signs(-5, -10);
    printf("\n");

    printf("=== 12. Find the unique element via XOR ===\n");
    demo_find_unique();
    printf("\n");

    printf("=== 13. Branchless absolute value ===\n");
    demo_fast_abs();
    printf("\n");

    printf("=== 14. Reverse the bits of a byte ===\n");
    demo_reverse_bits();
    printf("\n");

    printf("=== 15. Rotate bits left within a byte ===\n");
    demo_rotate();
    printf("\n");

    return 0;
}
